<?php

namespace Devy\UkrBookBundle\Repository;

use Devy\UkrBookBundle\Entity\Attribute;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * AttributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributeRepository extends EntityRepository
{
    /**
     * @return Attribute[]
     */
    public function getAllSortedByIsActive()
    {
        $qb = $this->createQueryBuilder('a')
            ->orderBy('a.is_active', 'DESC');
        try {
            $attributes = $qb->getQuery()->getResult();
        } catch (NoResultException $e) {
            $attributes = [];
        }
        return $attributes;
    }
}
