<?php

namespace Devy\UkrBookBundle\Repository;

use Devy\UkrBookBundle\Entity\Brand;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * BrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandRepository extends EntityRepository
{
    /**
     * @return Brand[]
     */
    public function getAllOrderedByIsActive()
    {
        $qb = $this->createQueryBuilder('b')
            ->orderBy('b.is_active', 'DESC');

        try {
            $brands = $qb->getQuery()->getResult();
        } catch (NoResultException $e) {
            $brands = [];
        }
        return $brands;
    }
}
