<?php

namespace Devy\UkrBookBundle\Repository;

use Devy\UkrBookBundle\Entity\Category;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    /**
     * @param boolean $onlyActive
     * @return Category[]
     */
    public function getTopLevel($onlyActive = true)
    {
        $qb = $this->createQueryBuilder('c')
            ->Where('c.Parent IS NULL');
        if ($onlyActive) {
            $qb->andWhere('c.is_active = true');
        }
        try {
            $categories = $qb->getQuery()->getResult();
        } catch (NoResultException $e) {
            $categories = array();
        }
        return $categories;
    }
}
