<?php

namespace Devy\UkrBookBundle\Repository;

use Devy\UkrBookBundle\Entity\Message;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    /**
     * @return Message[]
     */
    public function getAll()
    {
        $queryBuilder = $this->createQueryBuilder('m')
            ->orderBy('m.processed', 'DESC')
            ->addOrderBy('m.posted_at', 'DESC');

        try {
            $messages = $queryBuilder->getQuery()->getResult();
        } catch (NoResultException $e) {
            $messages = [];
        }
        return $messages;
    }

    /**
     * @return Message[]
     */
    public function getAllUnprocessed()
    {
        $queryBuilder = $this->createQueryBuilder('m')
            ->where('m.processed = false')
            ->orderBy('m.posted_at', 'DESC');

        try {
            $messages = $queryBuilder->getQuery()->getResult();
        } catch (NoResultException $e) {
            $messages = [];
        }
        return $messages;
    }
}
