<?php

namespace Devy\UkrBookBundle\Repository;

use Devy\UkrBookBundle\Entity\Order;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends EntityRepository
{
    /**
     * @return Order[]
     */
    public function getAll()
    {
        $queryBuilder = $this->createQueryBuilder('o')
            ->orderBy('o.status', 'ASC')
            ->addOrderBy('o.created_at', 'ASC')
            ->addOrderBy('o.updated_at', 'ASC');

        try {
            $orders = $queryBuilder->getQuery()->getResult();
        } catch (NoResultException $e) {
            $orders = [];
        }
        return $orders;
    }
}
