<?php

namespace Devy\UkrBookBundle\Repository;

use Devy\UkrBookBundle\Entity\Post;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    /**
     * @param int $limit
     * @return Post[]
     */
    public function getActive($limit = 5)
    {
        $qb = $this->createQueryBuilder('p')
            ->where('p.is_active = true')
            ->setMaxResults($limit);
        try {
            $posts = $qb->getQuery()->getResult();
        } catch (NoResultException $e) {
            $posts = [];
        }

        return $posts;
    }
}
