<?php

namespace Devy\UkrBookBundle\Repository;

use Devy\UkrBookBundle\Entity\Product;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    /**
     * @return Product[]
     */
    public function getAllSortedByIsActive()
    {
        $qb = $this->createQueryBuilder('p')
            ->orderBy('p.is_active', 'DESC');
        try {
            $products = $qb->getQuery()->getResult();
        } catch (NoResultException $e) {
            $products = [];
        }
        return $products;
    }

    /**
     * @param int $limit
     * @return Product[]
     */
    public function getLastAdded($limit = 12)
    {
        $qb = $this->createQueryBuilder('p')
            ->where('p.is_active = true')
            ->orderBy('p.created_at', 'DESC')
            ->setMaxResults($limit);
        try {
            $products = $qb->getQuery()->getResult();
        } catch (NoResultException $e) {
            $products = [];
        }
        return $products;
    }
}
