<?php

namespace Devy\UkrBookBundle\Repository;

use Devy\UkrBookBundle\Entity\Product;
use Devy\UkrBookBundle\Entity\Review;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * ReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends EntityRepository
{
    /**
     * @param Product $product
     * @param int|null $limit
     * @return Review
     */
    public function getActiveByProduct(Product $product, $limit = null)
    {
        $queryBuilder = $this->createQueryBuilder('r')
            ->where('r.is_active = true')
            ->andWhere('r.Product = :product')
            ->setParameter(':product', $product)
            ->orderBy('r.posted_at', 'DESC');
        if ($limit) {
            $queryBuilder->setMaxResults($limit);
        }
        try {
            $reviews = $queryBuilder->getQuery()->getResult();
        } catch (NoResultException $e) {
            $reviews = [];
        }
        return $reviews;
    }
}
