devy_ukr_book:
    resource: "@DevyUkrBookBundle/Resources/config/routing.yml"
    prefix:   /

user_routes:
    resource: "@UserBundle/Controller"
    type: annotation

frontend:
    resource: "@DevyFrontendBundle/Resources/config/routing.yml"


