Devy\UkrBookBundle\Entity\AttributeSet:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    name:
      type: string
      unique: true
      length: 45
      nullable: false
    is_active:
      type: boolean
      nullable: true
  oneToMany:
    Attributes:
      targetEntity: Devy\UkrBookBundle\Entity\Attribute
      mappedBy: AttributeSet
