Devy\UkrBookBundle\Entity\Category:
    type: entity
    table: category
    repositoryClass: Devy\UkrBookBundle\Repository\CategoryRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        oneToOne:
          parent_id:
            targetEntity: Category
            joinColumn:
              name: parent_id
              referencedColumnName: id
        name:
            type: string
            length: 255
            unique: true
        slug:
            type: string
            length: 255
            unique: true
        description:
            type: string
            length: 255
        is_active:
            type: boolean
            options:
                default: false
        created_at:
            type: datetime
        updated_at:
            type: datetime
            nullable: true
        deleted_at:
            type: datetime
            nullable: true
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue, setSlugValue ]
        preUpdate: [ setUpdatedAtValue, setSlugValue ]
        preDelete: [ setDeletedAtValue ]
