Devy\UkrBookBundle\Entity\Image:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    image:
      type: string
      length: 250
      nullable: true
  oneToOne:
    Product:
      targetEntity: Devy\UkrBookBundle\Entity\Product
      inversedBy: Image
      joinColumns:
        product_id:
          referencedColumnName: id
          unique: true
          onDelete: CASCADE
