Devy\UkrBookBundle\Entity\Message:
  type: entity
  repositoryClass: Devy\UkrBookBundle\Repository\MessageRepository
  table: Messages
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    subject:
      type: string
      length: 255
      nullable: false
    message:
      type: string
      length: 255
      nullable: false
    name:
      type: string
      length: 255
      nullable: true
    email:
      type: string
      length: 255
      nullable: false
    phone:
      type: string
      length: 255
      nullable: true
    processed:
      type: boolean
    posted_at:
      type: datetime
      nullable: true
  lifecycleCallbacks:
    prePersist: [prePersist]
