Devy\UkrBookBundle\Entity\Post:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    title:
      type: string
      length: 255
    text:
      type: text
    created_at:
      type: datetime
      nullable: true
    updated_at:
      type: datetime
      nullable: true
    is_active:
      type: boolean
      options:
        default: false
  lifecycleCallbacks:
    prePersist: ["setCreatedAtValue"]
    preUpdate: ["setUpdatedAtValue"]
