Devy\UkrBookBundle\Entity\ProductAttribute:
  type: entity
  id:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
  fields:
    value:
      type: string
      nullable: false
  manyToOne:
    Product:
      targetEntity: Devy\UkrBookBundle\Entity\Product
      inversedBy: ProductAttributes
      cascade: [persist]
      joinColumns:
        product_id:
          referencedColumnName: id
    Attribute:
      targetEntity: Devy\UkrBookBundle\Entity\Attribute
      inversedBy: ProductAttributes
      cascade: [persist]
      joinColumns:
        attribute_id:
          referencedColumnName: id
