Devy\UkrBookBundle\Entity\Profile:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    sf_guard_profile:
      type: string
      length: 45
      nullable: false
  oneToOne:
    User:
      targetEntity: Devy\UkrBookBundle\Entity\User
      mappedBy: Profile
