Devy\UkrBookBundle\Entity\Review:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    review:
      type: string
      length: 255
      nullable: false
  manyToOne:
    Product:
      targetEntity: Devy\UkrBookBundle\Entity\Product
      inversedBy: Reviews
      joinColumns:
        product_id:
          referencedColumnName: id
          onDelete: CASCADE
