Devy\UkrBookBundle\Entity\Review:
  type: entity
  repositoryClass: Devy\UkrBookBundle\Repository\ReviewRepository
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    review:
      type: string
      length: 255
      nullable: false
    score:
      type: integer
      nullable: false
    is_active:
      type: boolean
      options:
        default: false
  manyToOne:
    Product:
      targetEntity: Devy\UkrBookBundle\Entity\Product
      inversedBy: Reviews
      joinColumns:
        product_id:
          referencedColumnName: id
          onDelete: CASCADE
