Devy\UkrBookBundle\Entity\Subscriber:
  type: entity
  repositoryClass: Devy\UkrBookBundle\Repository\SubscriberRepository
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    email:
      type: string
      length: 255
      nullable: false
      unique: true
    is_active:
      type: boolean
      options:
        default: true
