attribute:
    path:     /
    defaults: { _controller: "DevyUkrBookBundle:Attribute:index" }

attribute_show:
    path:     /{id}/show
    defaults: { _controller: "DevyUkrBookBundle:Attribute:show" }

attribute_new:
    path:     /new
    defaults: { _controller: "DevyUkrBookBundle:Attribute:new" }

attribute_create:
    path:     /create
    defaults: { _controller: "DevyUkrBookBundle:Attribute:create" }
    requirements: { _method: post }

attribute_edit:
    path:     /{id}/edit
    defaults: { _controller: "DevyUkrBookBundle:Attribute:edit" }

attribute_update:
    path:     /{id}/update
    defaults: { _controller: "DevyUkrBookBundle:Attribute:update" }
    requirements: { _method: post|put }

attribute_delete:
    path:     /{id}/delete
    defaults: { _controller: "DevyUkrBookBundle:Attribute:delete" }
    requirements: { _method: post|delete }
