attribute:
    path:     /
    defaults: { _controller: "DevyUkrBookBundle:Attribute:index" }

attribute_new:
    path:     /new
    defaults: { _controller: "DevyUkrBookBundle:Attribute:new" }

attribute_edit:
    path:     /{id}/edit
    defaults: { _controller: "DevyUkrBookBundle:Attribute:edit" }
