brand:
    path:     /
    defaults: { _controller: "DevyUkrBookBundle:Brand:index" }

brand_new:
    path:     /new
    defaults: { _controller: "DevyUkrBookBundle:Brand:new" }

brand_edit:
    path:     /{id}/edit
    defaults: { _controller: "DevyUkrBookBundle:Brand:edit" }
