post:
    path:     /
    defaults: { _controller: "DevyUkrBookBundle:Post:index" }

post_new:
    path:     /new
    defaults: { _controller: "DevyUkrBookBundle:Post:new" }

post_edit:
    path:     /{id}/edit
    defaults: { _controller: "DevyUkrBookBundle:Post:edit" }

post_delete:
    path:     /{id}/delete
    defaults: { _controller: "DevyUkrBookBundle:Post:delete" }
    requirements: { _method: post|delete }
