product:
    path:     /
    defaults: { _controller: "DevyUkrBookBundle:Product:index" }

product_show:
    path:     /{id}/show
    defaults: { _controller: "DevyUkrBookBundle:Product:show" }

product_new:
    path:     /new
    defaults: { _controller: "DevyUkrBookBundle:Product:new" }

product_new_category:
    path:     /new/{category_id}
    defaults: { _controller: "DevyUkrBookBundle:Product:new" }
    requirements:
      category_id: \d+

product_edit:
    path:     /{id}/edit
    defaults: { _controller: "DevyUkrBookBundle:Product:edit" }

product_reviews:
    path:     /{id}/reviews
    defaults: { _controller: "DevyUkrBookBundle:Product:reviews" }

product_review_activate:
    path:     /review/activate/{id}
    defaults: { _controller: "DevyUkrBookBundle:Product:activateReview" }

product_review_deactivate:
    path:     /review/deactivate/{id}
    defaults: { _controller: "DevyUkrBookBundle:Product:deactivateReview" }
