product:
    path:     /
    defaults: { _controller: "DevyUkrBookBundle:Product:index" }

product_show:
    path:     /{id}/show
    defaults: { _controller: "DevyUkrBookBundle:Product:show" }

product_new:
    path:     /new
    defaults: { _controller: "DevyUkrBookBundle:Product:new" }

product_new_category:
    path:     /new/{category_id}
    defaults: { _controller: "DevyUkrBookBundle:Product:new" }
    requirements:
      category_id: \d+

product_edit:
    path:     /{id}/edit
    defaults: { _controller: "DevyUkrBookBundle:Product:edit" }
